fastlane_version "2.64.0"

default_platform :ios

## to run 
# fastlane beta
# OR
# fastlane beta test_email:a_ser@bk.ru

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|

    # pod install
    cocoapods

    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # let's just pring git changelog for help to remember
    puts changelog_from_git_commits

    # Release notes
    # Ask for a multi-line input
    # The user confirms their input by typing `END` and Enter
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
  
    # increment_build_number will increment for all targets simultaneously.
    # no way to increment only for one target currently
    # let's use plugin for fastline https://github.com/SiarheiFedartsou/fastlane-plugin-versioning
    #increment_build_number_in_plist(target: 'lsboutique')

    increment_build_number

    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'TryFastlane', 
        export_method: 'development',
        include_bitcode: false)

    emails = values[:test_email] ? values[:test_email] : ['a_ser@bk.ru'] # You can list more emails here
    groups = values[:test_email] ? values[:test_email] : 'testers' # You can define groups on the web and reference them here

    crashlytics(api_token: 'a58bddeb2bbbf8e2a2ee01ae3f4bf673f86f17c9',
             build_secret: '6189ea6bc48d19e08db31c6105148e41bacb93eee725f12480fafead169b2814',
                   emails: emails,
                   groups: groups,
                    notes: changelog,
            notifications: true) # Should this distribution notify your testers via email?

   # Commit the version bump
    commit_version_bump(force: true)

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
       slack_url: "https://hooks.slack.com/services/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",
       channel: "ios-dev",
       message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    )

  end
end
